const needs = [
  { title:'研究背景 / 综述', query:['研究背景'], hint:'了解情感 AI、智慧养老、数字健康与服务模式' },
  { title:'问卷变量 / 维度线索', query:['问卷变量'], hint:'建立情感 AI 使用体验与健康支持的变量池' },
  { title:'情感陪伴 / 使用接受', category:'情感陪伴与接受', hint:'找孤独感、情感支持、陪伴体验、信任和使用意愿' },
  { title:'交互可用性 / 适老设计', category:'交互设计与可用性', hint:'找语音交互、界面、操作负担与场景任务' },
  { title:'数字鸿沟 / 伦理安全', category:'伦理与数字包容', hint:'找隐私、自主性、拒用、人工兜底和风险边界' },
  { title:'家庭 / 代际支持', category:'代际支持与家庭关系', hint:'找亲子沟通、代际支持、孝道期望与孤独感' },
  { title:'健康管理 / 服务协同', category:'健康管理与协同服务', hint:'找社区健康管理、平台、服务流程和协同机制' },
  { title:'居家场景 / 智能终端', category:'空间终端与场景', hint:'找居家养老、智能家居、空间和终端需求' },
  { title:'认知支持 / 临床安全', category:'认知支持与临床边界', hint:'找 MCI、认知训练、跌倒风险与专业转介边界' }
];
const state={records:[],need:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function fillSelect(selector,values){const el=$(selector);[...new Set(values)].sort((a,b)=>a.localeCompare(b,'zh-CN')).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.append(o)});}
function currentText(){return [$('#search-input').value,$('#category-filter').value,$('#kind-filter').value,$('#priority-filter').value].filter(Boolean).join(' ');}
function matches(r){const q=$('#search-input').value.trim().toLowerCase();const c=$('#category-filter').value,k=$('#kind-filter').value,p=$('#priority-filter').value;const source=[r.id,r.title,r.reference,r.summary,r.application,r.population,r.measures,r.limitation,...r.tags,...r.keywords].join(' ').toLowerCase();if(q&&!source.includes(q))return false;if(c&&r.category!==c)return false;if(k&&r.kind!==k)return false;if(p&&r.priority!==p)return false;const need=state.need;if(!need)return true;return need.category?r.category===need.category:need.query.some(t=>r.tags.includes(t));}
function renderNeeds(){const grid=$('#need-grid');grid.innerHTML=needs.map((n,i)=>`<button class="need-card ${state.need===n?'active':''}" data-need="${i}"><h3>${esc(n.title)}</h3><p>${esc(n.hint)}</p><div class="tag-line">点击查看推荐文献 →</div></button>`).join('');grid.querySelectorAll('[data-need]').forEach(btn=>btn.addEventListener('click',()=>{state.need=needs[Number(btn.dataset.need)]; if(state.need.category)$('#category-filter').value=state.need.category; else $('#category-filter').value=''; $('#search-input').value='';renderNeeds();renderResults();document.querySelector('.search-panel').scrollIntoView({behavior:'smooth',block:'start'});}));}
function displayDocs(r){return r.documents.map((d,index)=>{const isPdf=d.format==='PDF';return `<button class="primary-button" data-open="${esc(r.id)}" data-doc="${index}">${isPdf?'打开全文':'下载 / 打开 CAJ'}</button>`}).join(' ');}
function renderResults(){const list=state.records.filter(matches);$('#result-summary').textContent=`找到 ${list.length} 篇推荐文献${state.need?' · 当前需求：'+state.need.title:''}`;const root=$('#results');if(!list.length){root.innerHTML='<div class="empty"><h3>未找到匹配文献</h3><p>请尝试更短的关键词，或清除类别与研究类型筛选。</p></div>';return;}root.innerHTML=list.map(r=>`<article class="paper-card"><div class="paper-top"><div><span class="paper-id">${esc(r.id)}</span><h3><button class="title-button" data-open="${esc(r.id)}" data-doc="0">${esc(r.title)}</button></h3><p class="paper-summary">${esc(r.summary)}</p></div><span class="priority ${esc(r.priority)}">${esc(r.priority)}阅读</span></div><p class="paper-ref">${esc(r.reference)}</p><div class="badge-row">${r.tags.map(t=>`<span class="badge">${esc(t)}</span>`).join('')}<span class="badge kind">${esc(r.kind)}</span></div><dl class="details"><div class="detail"><dt>可帮助解决的问题</dt><dd>${esc(r.application)}</dd></div><div class="detail"><dt>研究对象 / 样本</dt><dd>${esc(r.population)}</dd></div><div class="detail"><dt>指标 / 变量线索</dt><dd>${esc(r.measures)}</dd></div></dl><div class="paper-footer"><p class="paper-notice">${esc(r.notice)}</p><div>${displayDocs(r)}</div></div></article>`).join('');root.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openDocument(b.dataset.open,Number(b.dataset.doc))));}
function openDocument(id,docIndex){const r=state.records.find(x=>x.id===id),d=r?.documents[docIndex];if(!d)return;const url=encodeURI(d.filePath);if(d.format!=='PDF'){window.open(url,'_blank','noopener');return;}const dialog=$('#reader-dialog');$('#reader-title').textContent=r.title;$('#pdf-frame').src=url;$('#open-new-tab').href=url;if(!dialog.open)dialog.showModal();}
function closeReader(){const dialog=$('#reader-dialog');if(!dialog)return;if(dialog.open&&typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');window.setTimeout(()=>{$('#pdf-frame').src='about:blank';},0);}
async function boot(){try{const res=await fetch('data/literature.json');const data=await res.json();state.records=data.records;$('#record-count').textContent=data.count;fillSelect('#category-filter',state.records.map(x=>x.category));fillSelect('#kind-filter',state.records.map(x=>x.kind));renderNeeds();renderResults();$('#search-input').addEventListener('input',renderResults);['#category-filter','#kind-filter','#priority-filter'].forEach(s=>$(s).addEventListener('change',renderResults));$('#clear-needs').addEventListener('click',()=>{state.need=null;$('#category-filter').value='';renderNeeds();renderResults();});const dialog=$('#reader-dialog');$('#close-reader').addEventListener('click',event=>{event.preventDefault();event.stopPropagation();closeReader();},true);dialog.addEventListener('cancel',event=>{event.preventDefault();closeReader();});dialog.addEventListener('click',event=>{if(event.target===dialog)closeReader();});window.addEventListener('keydown',event=>{if(event.key==='Escape'&&dialog.open)closeReader();});}catch(e){$('#results').innerHTML=`<div class="empty"><h3>文献数据无法加载</h3><p>${esc(e.message)}</p></div>`;}}
boot();
